my_company_website/my_company_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('workers/', include('workers.urls'))
]

my_company_website/workers/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
app_name = 'workers' \
           ''
router = routers.DefaultRouter()
router.register('workers', views.WorkersView)

urlpatterns = [
    path('', views.workers_list, name='list'),
    path('json', include(router.urls)),
    path('<slug:slug>/', views.worker_detail, name='detail')
]

my_company_website/workers/models.py
from django.db import models

# Create your models here.
class Workers(models.Model):

    FIRST_NAME = models.CharField(max_length=255)
    LAST_NAME = models.CharField(max_length=255)
    EMAIL = models.CharField(max_length=255)
    PHONE_NUMBER = models.CharField(max_length=255)
    HIRE_DATE = models.DateField()
    JOB_ID = models.CharField(max_length=255)
    SALARY = models.DecimalField(max_digits=10, decimal_places=2)
    COMMISSION_PCT = models.DecimalField(max_digits=3, decimal_places=2)
    MANAGER_ID = models.IntegerField(default=None)
    DEPARTMENT_ID = models.IntegerField(default=None)
    slug = models.SlugField(null=False, unique=True)


    def __str__(self):
        return self.LAST_NAME

my_company_website/workers/views.py
from rest_framework import viewsets,permissions
from django.shortcuts import render, HttpResponse
from .models import Workers
from .serializers import WorkersSerializer

# Create your views here.


def workers_list(request):
    obj = Workers.objects.all
    context = {"object":obj}
    return render(request,'workers/workers_list.html', context)


def worker_detail(request, slug):
    # return HttpResponse(slug)
    worker = Workers.objects.get(slug=slug)
    return render(request, "workers/worker_detail.html", {'worker':worker})


class WorkersView(viewsets.ModelViewSet):
    queryset = Workers.objects.all()
    serializer_class = WorkersSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

my_company_website/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/styles.css">
</head>
<body>
     <div class="wrapper">
         <h1><a href="{% url 'workers:list' %}" >Workers</a> </h1>
         {% block content %}
         {% endblock %}
     </div>
</body>
</html>

my_company_website/templates/workers/worker_detail.html
{% extends 'base.html'%}
{% block content %}
<h1>My Company</h1>
<div class="worker-detail">
    <div class="worker">
        <h2>{{worker.FIRST_NAME}} {{worker.LAST_NAME}}</h2>
        <p>Email: {{worker.EMAIL}}</p>
        <p>Phone Number: {{worker.PHONE_NUMBER}}</p>
        <p>Hire Date: {{worker.HIRE_DATE}}</p>
        <p>Job ID: {{worker.JOB_ID}}</p>
        <p>Salary: {{worker.SALARY}}</p>
        <p>Comission PCT: {{worker.COMMISSION_PCT}}</p>
        <p>Manager ID: {{worker.MANAGER_ID}}</p>
        <p>Department ID: {{worker.DEPARTMENT_ID}}</p>
    </div>
</div>
{% endblock %}

my_company_website/templates/workers/workers_list.html
{% extends 'base.html'%}
{% block content %}
<h1>This is my workers list</h1>
<div class="workers">
    {%for worker in object%}
    <div class="worker">
       <h2>{{worker.id}} <a href="{% url 'workers:detail' slug=worker.slug %}"> {{worker.FIRST_NAME}} {{worker.LAST_NAME}}</a></h2>
    </div>
    {% endfor %}
</div>
{% endblock %}